(defun llenarDatos()
	(setq p (make-Persona))
	(print "Digite su nombre")
	(setf (Persona-nombre p) (read))
	(print "Digite su apellido")
	(setf (Persona-apellido p) (read))
	(print "Digite su edad")
	(setf (Persona-edad p) (read))
)